### PR TITLE
bashify xrandr string parsing

### PR DESCRIPTION
**Pull request by guss77**
Use bash native RE to filter and parse the xrandr output - IMHO this is more idiomatic and easier to understand than a bunch of grep and sed in an input redirection.

### CODE REVIEW

**Comment by mmikowski** [comment]
This looks like a nice improvement. We are moving over some unit tests to verify this doesn't break anything. I'll ping you soon with suggested next steps. Thank you for your contribution.

**Comment by mmikowski** [comment]
Hi Guss:

I have moved over the unit test for this utility in the JJ-2022-12 branch. Unfortunately, the changes do not pass. You can see this by switching to this branch, making your changes, and then running `test/test-script/runUnitTests 00710`. If you can get it to pass without changing the test, we should be able to proceed.

Cheers, Mike

**Review by mmikowski — CHANGES_REQUESTED** [review]
This doesn't pass the tests, as the regex doesn't appear to match and therefore the monitor adjustments are not applied. Please rebase to branch JJ-2022-12 and run `test/test-script/runUnitTests 00710` to test. If all asserts pass, we can proceed with the merge on that branch (jammy is reserved for releases).

**Comment by mmikowski** [comment]
Hi Guss:

Thank you for the contribution. I refactored the code to use the regex as you requested. This passes regression tests, shellcheck -x, and IntelliJ BashSupportPro checks, and I pushed it to the JJ-2022-12 branch. I will close this PR as this has now been addressed and will be updated in the next release. Please reopen if you wish.

```bash
_calcDisplaySetListFn () {
  declare _raw_str _x_int _line _solve_line;
  _raw_str="$(xrandr --listmonitors)";
  _logLineFn 'Pre-adjust xrandr monitor output:' "${_raw_str}";

  _x_int=0;
  while read -r _line; do
    if [[ "${_line}" =~ ^\ +[0-9]+:\ \+\**([^\ ]+)\ ([0-9]+)/[0-9]+x([0-9]+)/[0-9]+\+([0-9]+)\+ ]]; then
      if [ "${_x_int}" != "${BASH_REMATCH[4]}" ]; then
        _solve_line="$(IFS='|'; echo "${BASH_REMATCH[*]:1:3}")";
        _displaySetList+=( "${_solve_line}|${_x_int}|0" );
      fi
      (( _x_int += BASH_REMATCH[2] ));
    fi
  done <<<"${_raw_str}";
  _logLineFn 'SetList created:' "${_displaySetList[*]}";
}
```

**Comment by guss77** [comment]
Thank you - this is actually better: just one loop.

**Pull request closed without merging**
