### PR TITLE
Repackage kfocus-power as a Qt Quick app + some hacks

### PR DESCRIPTION
**Pull request by ArrayBolt3**
The hacks:

1. The kfocus-bug-power icon is now used as the app icon.
2. The default window height has been reduced to look better.
3. The window height extends itself if a message is returned from kfocus-fan-set.

Note that the kfocus-power.qml file is now a binary app, kfocus-power-bin. This increases complexity, but also unlocks the ability to do things like set the app icon (which you can't do from QML, but can do from C++). It also avoids using qmlscene, which is disclaimed as a prototyping tool and not a launcher at https://doc.qt.io/qt-5/qtquick-qmlscene.html.

### CODE REVIEW

**Comment by eeickmeyer** [comment]
If this is going to be compiled code, then debian/control for kfocus-power must also change to Architecture: amd64.

**Comment by ArrayBolt3** [comment]
That, and we need some way of working the qmake build system into the picture so that we can get a buildable Makefile.

**Comment by eeickmeyer** [comment]
Yes, I was about to mention that. Also build dependencies. Basically, this opens a can of worms.

**Comment by ArrayBolt3** [comment]
I didn't think about that. Also the kfocus-power-script is still using qmlscene, which would need swapped out with this.

This may be in Draft stage for a while :P I wish we could have just kept using qmlscene, but you can't set an app icon in QML, only in C++, and if Qt says qmlscene is not to be used in production, it's probably wise to listen to them.

**Comment by ArrayBolt3** [comment]
Currently I'm working on making a separate kfocus-power-bin package. The existing kfocus-power package won't have to change at all. All of the build deps, qmake, arch dependency, and other stuff can be contained in kfocus-power-bin, and the existing packaging can be left as-is.

**Comment by ArrayBolt3** [comment]
@eeickmeyer OK, packaging should be a bit better. I still need to update a script and verify that said updated script actually works though.

**Comment by ArrayBolt3** [comment]
OK, that should finish switching to kfocus-power-bin.

Also found and fixed a kfocus-fan-set bug.

**Comment by ArrayBolt3** [comment]
I'm *tentatively* marking this as ready for review, since I think it is likely done or close to done... but I would urge some extra-close checking just in case. Plus it's almost 2 AM here, so my tired brain may have done something wrong.

**Comment by ArrayBolt3** [comment]
Oof, forgot to include ${shlibs:Depends} in the Control file. Fixing.

**Comment by ArrayBolt3** [comment]
OK, I think that should be it! Might need the JJ-2023-03 branch merged in since the package-tools packages wouldn't install for me due to something about tuxedo-keyboard, which I think is something new in the other branch.

**Comment by eeickmeyer** [comment]
> OK, I think that should be it! Might need the JJ-2023-03 branch merged in since the package-tools packages wouldn't install for me due to something about tuxedo-keyboard, which I think is something new in the other branch.

You need to merge the packaging changes from JJ-2023-03 in to your dev branch because there was a release due to changes *from* tuxedo-keyboard. There was a regression (really, a complete rewrite of the API) in tuxedo-keyboard, so we forked the old version.

**Comment by mmikowski** [comment]
Thanks @eeickmeyer, consider it done.

**Pull request merged**
